services:
  - type: web
    name: portfolio
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "portfolio-abc123.onrender.com"  # Replace with your actual URL
      - key: PORT
        value: 8000
    autoDeploy: true
    healthCheckPath: /
    numInstances: 1
